name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - name: Checkout
        uses: actions/checkout@v4

      # Устанавливаем JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Делаем gradlew исполняемым
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Собираем проект из корня
      - name: Build with Gradle
        run: ./gradlew build

      # Загружаем apk как артефакт
      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: app/build/outputs/
